# Generated by Django 5.1.4 on 2025-01-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
